set t_Co=16
set encoding=utf8

set nocompatible
set hidden                  " Hide buffers instead of closing them (useful for :e)

set showcmd                 " Show partial command as it is typed
set showmode                " Show INSERT, REPLACE or VISUAL
set showmatch               " When a bracket is inserted, briefly jump to the matching one
set nowrap                  " Don't soft-wrap
set number
set virtualedit=block       " Move freely into null-space when in visual block mode
set splitright              " When splitting to view a new file, open it on the right
set splitbelow              " When splitting to view a new file, open it at the bottom

set wildignore=*.swp,*.pyc  " Ignore these patterns when tab-completing
set wildmode=longest:full,full
set wildmenu

set updatetime=100
set timeout timeoutlen=1000 ttimeoutlen=0

" Searching options
set hlsearch                " Highlight search term
set incsearch               " Show search matches as you type
"set smartcase               " Ignore case when search is all lowercase

" Color options
syntax on
set background=light

"highlight Cursor term=NONE cterm=NONE ctermbg=DarkGray
highlight MatchParen term=none ctermbg=Black ctermfg=Red

highlight LineNr ctermfg=DarkGray
set cursorline
set cursorlineopt=number
highlight clear CursorLineNr
highlight CursorLineNr ctermfg=White

highlight SignColumn ctermbg=None

highlight clear Visual
highlight Visual cterm=reverse

highlight clear Search
highlight Search ctermbg=DarkYellow ctermfg=Black

highlight clear Todo
highlight Todo ctermfg=Yellow ctermbg=Black

highlight ColorColumn ctermbg=Black
set colorcolumn=79
autocmd FileType javascript set colorcolumn=100

set fillchars+=vert:┃
highlight clear VertSplit
highlight VertSplit cterm=none ctermbg=none ctermfg=Black


highlight Folded ctermfg=Cyan ctermbg=none
set fillchars+=fold:\ "

" GUI systems integration (mouse, clipboard)
set mouse=a
set ttymouse=xterm2
if has('mouse_sgr')
    set ttymouse=sgr
endif
set ttyscroll=1         " https://wiki.archlinux.org/index.php/Vim/.vimrc
set clipboard=unnamed   " Copy/paste from X

" Tell vim to remember certain things when we exit
"  '100   :  marks will be remembered for up to 100 previously edited files
"  "10000 :  will save up to 1000 lines for each register
"  :20    :  up to 20 lines of command-line history will be remembered
"  n...   :  where to save the viminfo files
set viminfo='100,\"10000,:20,n~/.vim/viminfo

" Tabs and indentation
set tabstop=4
set softtabstop=4
set expandtab
set autoindent
"set smartindent
set nocindent
set shiftwidth=4            " Number of spaces used for auto-indent
set smarttab                " Insert tabs on the start of a line according to shiftwidth, not tabstop
set backspace=indent,eol,start " Backspace over auto-indent, line breaks and past the start of the insert

" Tabs for HTML (and templates) and CSS
" TODO This should be replaced by settings in plugins
autocmd FileType html,htmldjango,mako,css,javascript,json set tabstop=2
autocmd FileType html,htmldjango,mako,css,javascript,json set softtabstop=2
autocmd FileType html,htmldjango,mako,css,javascript,json set shiftwidth=2

" Remove extraneous whitespace from the end of a buffer.
autocmd BufWritePre,FileWritePre,FileAppendPre * :%s/\(\S\)\@<=\s\+$//e
autocmd BufWritePre,FileWritePre,FileAppendPre * :%s/[ \t\r]\+$//e

" Highlight HTML like django
"autocmd FileType html set filetype=htmldjango

" Status line
set laststatus=2                " status line even with only one window
set statusline=[%n]             " buffer number
set statusline+=%(\ %m%r%h%)    " [+][RO][Help]
set statusline+=\ %f            " file name
set statusline+=%=              " start right aligned items
set statusline+=%y              " [filetype]
set statusline+=\ [%3b:0x%02B]  " byte at cursor, in hex
set statusline+=\ %2c,%3l/%L    " col, line/maxlines

highlight StatusLine term=none cterm=none gui=none ctermbg=DarkGreen ctermfg=Black
highlight StatusLineNC term=none cterm=none gui=none ctermbg=DarkGray ctermfg=LightGray
autocmd InsertEnter * highlight StatusLine ctermbg=DarkYellow
autocmd InsertLeave * highlight StatusLine ctermbg=DarkGreen

" === Better default keys

nnoremap n nzz
nnoremap N Nzz
nnoremap } }zz
nnoremap { {zz
nnoremap <Space> <C-w><C-w>

noremap ; :
noremap <Leader>; ,
noremap , ;

nnoremap <LeftMouse> m'<LeftMouse>

" === Switch numbers and symbols in insert mode
"inoremap 1 !
"inoremap ! 1
"inoremap 2 @
"inoremap @ 2
"inoremap 3 #
"inoremap # 3
"inoremap 4 $
"inoremap $ 4
"inoremap 5 %
"inoremap % 5
"inoremap 6 ^
"inoremap ^ 6
"inoremap 7 &
"inoremap & 7
"inoremap 8 *
"inoremap * 8
"inoremap 9 (
"inoremap ( 9
"inoremap 0 )
"inoremap ) 0

" === Utility keys

" highlight word under cursor
nnoremap <F10> :set hls<CR>:let @/="<C-r><C-w>"<CR>
nnoremap <F12> :nohls<CR>

" cursor crosshair
"hi CursorLine   cterm=NONE ctermbg=darkyellow ctermfg=white guibg=darkyellow guifg=white
hi CursorColumn cterm=NONE ctermbg=DarkGray ctermfg=Black
" :nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
nnoremap <F11> :set cursorcolumn!<CR>

" highlight text after column 79
"hi bigline none
"match bigline /\%80v.\+/
"nnoremap <F10> :hi bigline ctermbg=red ctermfg=white guibg=#592929<CR>
"nnoremap <C-F10> :hi bigline none<CR>

" ssh mode: hide numbers, unset mouse, set paste
"nnoremap <F9> :set nonu<CR>:set mouse=""<CR>:set paste<CR>:GitGutterSignsToggle<CR>
"nnoremap <C-F9> :set nu<CR>:set mouse=a<CR>:set nopaste<CR>:GitGutterSignsToggle<CR>

" === Misc settings

" mkview options (Vim scripts that restore the contents of the current window)
set viewoptions=cursor,folds,options
set viewdir=~/.vim/view
" :help directory, in particular trailing // uses the whole file path for the name
set directory=~/.local/state//

" maintain the buffer's view options and restore them when coming back
" (in particular topline so that it doesn't scroll the current line to middle of screen)
" This emulates a windowbuffer-local by having a window-local dictionary with buffer numbers as keys
"au VimEnter,WinEnter * if(!exists('w:bufsettings')) | let w:bufsettings = {} | endif
"au BufLeave * let w:bufsettings[bufnr('%')] = winsaveview()
"au BufEnter * if(exists('w:bufsettings['.bufnr('%').']')) | call winrestview(w:bufsettings[bufnr('%')]) | endif

" Demonstrate the triggering of (Win|Buf)(Enter|Leave) events
"au VimEnter * let g:EventsHist = []
"au WinEnter * call add(g:EventsHist, 'WE-'.winnr().'-'.bufnr('%'))
"au WinLeave * call add(g:EventsHist, 'WL-'.winnr().'-'.bufnr('%'))
"au BufEnter * call add(g:EventsHist, 'BE-'.winnr().'-'.bufnr('%'))
"au BufLeave * call add(g:EventsHist, 'BL-'.winnr().'-'.bufnr('%'))


" === Vundle
" https://github.com/gmarik/vundle

""" filetype off                    " required!
"""
""" set rtp+=~/.vim/bundle/Vundle.vim
""" call vundle#begin()
"""
""" " let Vundle manage Vundle
""" Plugin 'gmarik/Vundle.vim'
"""
""" " ---
""" "Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
""" "Plugin 'tpope/vim-fugitive'
""" Plugin 'airblade/vim-gitgutter'
""" "Plugin 'amitdev/vimpy'
""" Plugin 'andviro/flake8-vim'
""" Plugin 'hynek/vim-python-pep8-indent'
""" Plugin 'pangloss/vim-javascript'
""" Plugin 'Shutnik/jshint2.vim'
""" Plugin 'kchmck/vim-coffee-script'
""" Plugin 'vim-scripts/nginx.vim'
"""
""" " My bundles here:
""" " original repos on github
""" "Plugin 'Lokaltog/vim-easymotion'
""" "Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
""" "Plugin 'tpope/vim-rails.git'
""" " vim-scripts repos
""" "Plugin 'L9'
""" "Plugin 'FuzzyFinder'
""" " non github repos
""" "Plugin 'git://git.wincent.com/command-t.git'
""" " git repos on your local machine (ie. when working on your own plugin)
""" "Plugin 'file:///Users/gmarik/path/to/plugin'
""" " ...
"""
""" call vundle#end()
""" filetype plugin indent on     " required!
"
" Brief help
" :Plugin        - list configured bundles
" :Plugin(!)     - install(update) bundles
" :Plugin(!) foo - search(or refresh cache first) for foo
" :Plugin(!)     - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Plugin command are not allowed..


" --- flake8-vim options ---
let g:PyFlakeOnWrite = 0
let g:PyFlakeMaxLineLength = 120

" --- nginx.vim setup ---
au BufRead,BufNewFile /etc/nginx/*,/home/tek/etc/nginx/* if &ft == '' | setfiletype nginx | endif

