LS_OPTIONS="--color=tty -F -b -T 0"
export LS_OPTIONS
alias ll="ls $LS_OPTIONS -l"
alias lall="ls $LS_OPTIONS -l -a"

alias grep="grep --color=auto"
alias G="grep -rn --exclude=*\.svn* "
alias F="find . -name "

# Git aliases
alias glog="git log --format=format:'%w(200,0,4)%Cblue%aN%Creset: %s'"
alias glogful="git log --format=format:'%Cblue%aN%Creset: %Cgreen%H%Creset%n%B'"
alias gst="git status"
alias gd="git diff HEAD"

